language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: X6wqANOHjJ3yIsCGr9xjZpRoqOVa61OHp1VjsZh+CPsXAj66rS0f5YRRPbX0cJat0j4UGNQUsQyox27r4paEu1Wjpxaur81bIsEtAYapgd8W4yrnsDd5Bei3utPOxBnpsA9LTXm3R7rv1Jf6eC55CxjsYgcZgUDD1PwAdji0vllg7uiLTd87iCbCC5uI6sjWlUacttyQcEgkmz4PcI64K9Wr4rw3FF63E9mSGnH1vae8xnoUdBWUA6XqOQDJaLTOEnAQqtmwdExTLLsJ8sci4ej2e68a/h+NoT10M8USwwi8L2aFyvrsu6a/X6QOkyWhuPUKvekjXhScMtIuh0K/2uq862yCw6q9vWdnGcwfkAonogBhtzAh5r4P9h05FSCTuowIRDNvatVMqyAUfYz2pfpCoyVEEV52DAkSNDQZY5mT+H99FkhKYM+PmtvRZUUXCCXXcIh3td7VlnODcjj9ciYdzHikSsGkXhDjY9LXlaG31MdEBZrhxT6QtdEegysIVKUE4OwyXc/56MfD11JmnYoaXrthNHtKkMplO1YBhk6hNzai2C/K2TgvAZqOysP0lztYziG3L93+FLtC/QMt5JG6a4T++O7/ZY7Oj4q3oFpUOjWmk0q56QC9D8qiLGEC/Iax45HbAiDU1Z6zt3B7GlzmGRuHfhUcZlVLoAky4g4=
    app: yasinisayildirim1711012007
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- node_modules/.bin/newman run tests/apiTest.postman_collection.json -e tests/Test.postman_environment.json
