language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: FKpnRt5ZSWwpa7FxBcm8clmAL7zYggLYK5DdFwUF7DW1OLjK846dbsPG4nxiwrfuB7f4e2BIiilvW3rak8232460cnod3yRYGw9iqQMZYOBxiHblxRJFQ2myUvg6mG3E64Ui0bkM4pCJ8AdQUe/+U6K55ugLyeh/WuepkZe3/KnnXaJmFQo23FKWMxPv/VpXxhrhfU6HeoQyJ7SS89udli6aqx8ufiPnA9AFkOB41KinTgqrVpJlujBQ4rtuyUqWBoOsyFh5Nst4QkaIz5F71h+Vg4q/tJjYZSJ7z9xUx/sBtVsHj2//X3IKLPxCs6Ntf2X3kvbNCKi2M2cVRnnvk2sSGsbVPW18+X2c5lGKcevQl8RZGb/SH+ju2CzxQuyiZ96n8CiHnKgFT1YN+U2G2rg02LYjBu2TdPzU2FcQ45EQP7qUs3+bCZgQB4LVSuFvUKHkOR0SD6n9WTJ/ytAP0e77DQbK9dwog7M2GFWS2IunmPgRe5BbiGWdBFA76eUO0+pyYOMwC0Cb5Oaldq5RBY2jcLWNHZAG0qHsMupJUiGAvllCpQKCF8xuCnkVTjCWAggFmHAjImKqBmQh+jYX67KApbXsOD5x3vuhASom5Nd+aofb5WiIZ2sd8LQa+Pg4TFtS69UBSBkGKTPxovBGxLmjEAm1OBb7kKIJpU1a7F8=
  app: yasinisayildirim1711012007
  on:
    repo: redsfyre/mekan32
  skip_cleanup: 'true'
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- node_modules/.bin/newman run tests/apiTest.postman_collection.json -e tests/Test.postman_environment.json
